### ISSUE TITLE
Blinkt dependency installation error 

### ISSUE THREAD

**Issue by AndiCui** [pimoroni/get#105]
https://github.com/pimoroni/blinkt/issues/28

python-dev is not installed by the one-line installer, which the version from pip requires

**Comment by RogueM** [comment]
cheers for the heads up... the problem is not the python-dev package missing, the problem is that we tried to enforce reinstalling the libs afresh and apparently the -I flag is recursive and treats all the packages dependencies that way.

In this instance it is trying to reinstall RPi.GPIO, which for which attempt of compilation will fail unless python-dev is present.

**Comment by AndiCui** [comment]
@Rogue got ya. Remember also to check compatibility on a system without git package. Remember fail to copy the example once

**Comment by RogueM** [comment]
all the scripts should have git as part of the 'full install' at this point. It's a better system as it means you can opt-out of installing examples altogether... particularly useful on Jessie Lite, where just installing git would take ages. Then again you probably will want it for other reasons ;-)

**Comment by AndiCui** [comment]
I noticed. If I recall it correctly, it failed to GIT the stuff on a full install. I got an empty ~/Pimoroni/blahblahblah.

**Comment by RogueM** [comment]
It's entirely possible there are (still) bugs, some being script specific... the blinkt OLI seems to install both git and examples right now.
