### ISSUE TITLE
enviro+ build error, Invalid Syntax in sounddevice.py

### ISSUE THREAD

**Issue by gparsons2** [pimoroni/get#209]
Building on Raspberry Pi Zero WH, current full Raspbian Buster 5.4.51+, using instructions at https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-enviro-plus, i.e. "sudo ./install.sh". Error:
```
file _sounddevice.py (for module _sounddevice) not found
  File "build/bdist.linux-armv6l/egg/sounddevice.py", line 2377
    repr(list(conversion_dict))) from e
                                    ^
SyntaxError: invalid syntax
```
I think the issue is sounddevice.py:2377 needs a ".keys()" after "conversion_dict":
`repr(list(conversion_dict.keys()))) from e`

The build does complete after above error and code runs, though I assume audio functions won't work!

**Comment by Gadgetoid** [comment]
The issue is that `from e` is not valid Python 2.x syntax, it looks like `sounddevice` dropped Python 2 support in version 0.4.0.

Python 2.x releases: https://pypi.org/project/sounddevice/0.3.15/#files

No Python 2.x releases: https://pypi.org/project/sounddevice/0.4.0/#files

You can probably fix this temporarily by running: `sudo python -m pip uninstall sounddevice` followed by `sudo python -m pip install sounddevice==0.3.15`.

I'll have to pin enviro+ to the older version for now, since we're still phasing out Python 2.x support.

**Comment by rezzorix** [comment]
> You can probably fix this temporarily by running: `sudo python -m pip uninstall sounddevice` followed by `sudo python -m pip install sounddevice==0.3.15`.

"probably" - not so shy... ;)
I have tested it and this is in fact fixing it; however thats ok as a temporary workaround only and should be properly fixed.

**Comment by rylanb** [comment]
I hit this issue today trying to run the one time install script. 

I don't really need the sound device stuff, but seems like the script should maybe move sounddevice into python 3 land?

**Comment by Gadgetoid** [comment]
I've dropped Python 2 support from Enviro Plus as of v0.0.5, which should fix this.
