### ISSUE TITLE
unicornhat script on Jessie

### ISSUE THREAD

**Issue by RogueM** [pimoroni/get#3]
tested against Jessie img 2015-0-24, straight after first boot.

I can confirm previous reports that it does not work. It simply outputs:

"Installing UnicornHat requirements...

Checking for python-pip...
python-pip already installed."

I have a lead as to  what could be wrong but I need to investigate further before I formulate a possible cause.

**Comment by RogueM** [comment]
right I am not sure why you are doing what the calls for 

        apt_pkg_install "python-pip"
        apt_pkg_install "python-dev"
        apt_pkg_install "python3-pip"
        apt_pkg_install "python3-dev"

as far as I can tell those are queries and you never actually proceed to install the dependencies?

it should be replaced by:
sudo apt-get --force-yes --yes install pkg1 pkg2 pkg3...

At least it works for me. Am I missing something in your code that makes my assessment incorrect?

**Comment by RogueM** [comment]
I tested against Wheezy img 2015-05-05, straight after first boot... I'm afraid the variation of the story is not good:

+ it insalled python-pip

Then stops. If you re-run it, same above. It seems like the package script is only geing called once, for the first call to apt_pkg_install (package script).

**Comment by RogueM** [comment]
Fix submitted PR#4

**Comment by Gadgetoid** [comment]
Awesome work. I'd like to be able to use package dep lists, the "array" of items you've used, as a method of making all the installer scripts a little more standardised. Though I'm still not sure it's worth the effort with a replacement *hopefully* coming. I'll get this pushed up to get for final testing.

I'm not massively concerned about thoroughly testing things, beyond a cursory check for anything explodey, since it just slows things down. People will normally drop a forum post, support ticket, tweet, etc if something goes wrong. Yup- I'm admitting to pushing sometimes shonky code and fixing it with another push :D

**Comment by RogueM** [comment]
I'm more than happy to standardise the install scripts. I don't think it's a big deal at all, I'm used to that kind of things, with 300+ installers you have to and learn quickly that rolling things across the board save you time later on, when you have to troubleshoot the corner cases ;-)

**Comment by RogueM** [comment]
I'm started going through them, without taking a lot of precaution it seems to be relatively effortless so I'll hack away and do them all. Let's close this issue since this particular one is done and live.
